resources:
- ../../base


namespace: dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: node-app
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
- path: route-patch.yaml
